# Staging environment settings
logging.level.com.gcs.quartz=INFO

# Logging Job Configuration for Staging
job.logging.log-separator=========================================
job.logging.job-title=Quartz Job Executed - Weekday Scheduler [STAGING]
job.logging.execution-time-label=Execution Time:
job.logging.job-name-label=Job Name:
job.logging.job-group-label=Job Group:
job.logging.trigger-name-label=Trigger Name:
job.logging.next-fire-time-label=Next Fire Time:
job.logging.date-time-format=yyyy-MM-dd HH:mm:ss
