# Quartz properties for dev environment
org.quartz.scheduler.instanceName=QuartzSchedulerDev
org.quartz.threadPool.threadCount=5
org.quartz.jobStore.class=org.quartz.simpl.RAMJobStore
spring.quartz.job-store-type=memory

